version: '3'

services:

  web:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: urlcut_web:latest
    container_name: urlcut-web
    command: >
      sh -c "python manage.py migrate
             python manage.py ensure_superuser --email="admin@example.com" --password="testpass123"
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./urlcut:/home/django/app   # bind mount for development
    ports:
      - "8000:8000"
    env_file:
      - ./compose/django/.env
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:14-alpine
    container_name: urlcut-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=urlcut_db
      - POSTGRES_USER=urlcut_user
      - POSTGRES_PASSWORD=testpass123

  rabbitmq:
    image: rabbitmq:alpine
    container_name: urlcut-rabbitmq
    ports:
      - "5672:5672"
    restart: always

  worker:
    image: urlcut_web:latest
    container_name: urlcut-worker
    command: celery -A urlcut worker -l INFO
    volumes:
      - ./urlcut:/home/django/app
    env_file:
      - ./compose/django/.env
    depends_on:
      - web
      - rabbitmq

  scheduler:
    image: urlcut_web:latest
    container_name: urlcut-scheduler
    command: celery -A urlcut beat -l INFO
    volumes:
      - ./urlcut:/home/django/app
    env_file:
      - ./compose/django/.env
    depends_on:
      - web
      - rabbitmq

volumes:
  postgres_data:
