# Generated by Django 4.1.8 on 2023-04-27 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.URLField(verbose_name='Target URL')),
                ('key', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Key')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Number of visits')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiry date')),
            ],
            options={
                'db_table': 'mapping',
            },
        ),
    ]
